git clone https://github.com/FiveM-LSRP/ls-safecrack   resources/[ls]/ls-safecrack &&
git clone https://github.com/FiveM-LSRP/ls-progressbar   resources/[ls]/ls-progressbar &&
git clone https://github.com/FiveM-LSRP/ls-interactsound   resources/[ls]/ls-interactsound &&
git clone https://github.com/FiveM-LSRP/ls-mhack   resources/[ls]/ls-mhack &&
git clone https://github.com/FiveM-LSRP/ls-queue   resources/[ls]/ls-queue &&
git clone https://github.com/FiveM-LSRP/ls-emotes   resources/[ls]/ls-emotes &&
git clone https://github.com/FiveM-LSRP/ox_fuel   resources/[ls]/[ox]/ox_fuel &&
git clone https://github.com/FiveM-LSRP/ox_lib   resources/[ls]/[ox]/ox_lib &&
git clone https://github.com/FiveM-LSRP/ox_target   resources/[ls]/[ox]/ox_target &&
git clone https://github.com/FiveM-LSRP/ox_doorlock   resources/[ls]/[ox]/ox_doorlock &&
git clone https://github.com/FiveM-LSRP/ox_inventory   resources/[ls]/[ox]/ox_inventory &&
git clone https://github.com/FiveM-LSRP/ls-core   resources/[ls]/ls-core &&
git clone https://github.com/FiveM-LSRP/ls-adminmenu   resources/[ls]/ls-adminmenu &&
git clone https://github.com/FiveM-LSRP/ls-multicharacter   resources/[ls]/ls-multicharacter &&
git clone https://github.com/FiveM-LSRP/ls-vehiclesales   resources/[ls]/ls-vehiclesales &&
git clone https://github.com/FiveM-LSRP/ls-vehicleshop   resources/[ls]/ls-vehicleshop &&
git clone https://github.com/FiveM-LSRP/ls-prison   resources/[ls]/ls-prison &&
git clone https://github.com/FiveM-LSRP/pefcl   resources/[ls]/[pe]/pefcl &&
git clone https://github.com/FiveM-LSRP/ls-pefcl   resources/[ls]/[pe]/ls-pefcl &&
git clone https://github.com/FiveM-LSRP/npwd   resources/[ls]/[pe]/npwd &&
git clone https://github.com/FiveM-LSRP/ls-npwd   resources/[ls]/[pe]/ls-npwd &&
git clone https://github.com/FiveM-LSRP/ls-hud   resources/[ls]/[ps]/ls-hud &&
git clone https://github.com/FiveM-LSRP/ls-ui   resources/[ls]/[ps]/ls-ui &&
git clone https://github.com/FiveM-LSRP/ls-mdt   resources/[ls]/[ps]/ls-mdt &&
git clone https://github.com/FiveM-LSRP/ls-dispatch   resources/[ls]/[ps]/ls-dispatch &&
git clone https://github.com/FiveM-LSRP/ls-drugprocessing   resources/[ls]/[ps]/ls-drugprocessing &&
git clone https://github.com/FiveM-LSRP/ls-buffs   resources/[ls]/[ps]/ls-buffs &&
git clone https://github.com/FiveM-LSRP/ls-signrobbery   resources/[ls]/[ps]/ls-signrobbery &&
git clone https://github.com/FiveM-LSRP/ls-walking   resources/[ls]/[ps]/ls-walking &&
git clone https://github.com/FiveM-LSRP/ls-management   resources/[ls]/ls-management &&
git clone https://github.com/FiveM-LSRP/ls-emergencyservices   resources/[ls]/ls-emergencyservices &&
git clone https://github.com/FiveM-LSRP/ls-vehiclefailure   resources/[ls]/ls-vehiclefailure &&
git clone https://github.com/FiveM-LSRP/ls-weathersync   resources/[ls]/ls-weathersync &&
git clone https://github.com/FiveM-LSRP/ls-policeservices   resources/[ls]/ls-policeservices &&
git clone https://github.com/FiveM-LSRP/ls-apartments   resources/[ls]/ls-apartments &&
git clone https://github.com/FiveM-LSRP/ls-vehiclekeys   resources/[ls]/ls-vehiclekeys &&
git clone https://github.com/FiveM-LSRP/ls-vehicleservices   resources/[ls]/ls-vehicleservices &&
git clone https://github.com/FiveM-LSRP/ls-tune   resources/[ls]/ls-tune &&
git clone https://github.com/FiveM-LSRP/ls-spawn   resources/[ls]/ls-spawn &&
git clone https://github.com/FiveM-LSRP/ls-skillbar   resources/[ls]/ls-skillbar &&
git clone https://github.com/FiveM-LSRP/ls-pico   resources/[ls]/ls-pico &&
git clone https://github.com/FiveM-LSRP/ls-cityservices   resources/[ls]/ls-cityservices &&
git clone https://github.com/FiveM-LSRP/ls-minigame   resources/[ls]/ls-minigame &&
git clone https://github.com/FiveM-LSRP/ls-commandbinds   resources/[ls]/ls-commandbinds &&
git clone https://github.com/FiveM-LSRP/ls-appearance   resources/[ls]/ls-appearance &&
git clone https://github.com/FiveM-LSRP/ls-lockpick   resources/[ls]/ls-lockpick &&
git clone https://github.com/FiveM-LSRP/ls-interior   resources/[ls]/ls-interior &&
git clone https://github.com/FiveM-LSRP/ls-menu   resources/[ls]/ls-menu &&
git clone https://github.com/FiveM-LSRP/ls-input   resources/[ls]/ls-input &&
git clone https://github.com/FiveM-LSRP/ls-loading   resources/[ls]/ls-loading