git clone https://github.com/qbcore-framework/safecracker   resources/[ls]/ls-safecrack &&
git clone https://github.com/Project-Sloth/progressbar   resources/[ls]/ls-progressbar &&
git clone https://github.com/qbcore-framework/interact-sound   resources/[ls]/ls-interactsound &&
git clone https://github.com/qbcore-framework/mhacking   resources/[ls]/ls-mhack &&
git clone https://github.com/qbcore-framework/connectqueue   resources/[ls]/ls-queue &&
git clone https://github.com/qbcore-framework/dpemotes   resources/[ls]/ls-emotes &&
git clone https://github.com/overextended/ox_fuel   resources/[ls]/[ox]/ox_fuel &&
git clone https://github.com/overextended/ox_lib   resources/[ls]/[ox]/ox_lib &&
git clone https://github.com/overextended/ox_target   resources/[ls]/[ox]/ox_target &&
git clone https://github.com/overextended/ox_doorlock   resources/[ls]/[ox]/ox_doorlock &&
git clone https://github.com/overextended/ox_inventory   resources/[ls]/[ox]/ox_inventory &&
git clone https://github.com/qbcore-framework/qb-core   resources/[ls]/ls-core &&
git clone https://github.com/qbcore-framework/qb-adminmenu   resources/[ls]/ls-adminmenu &&
git clone https://github.com/qbcore-framework/qb-multicharacter   resources/[ls]/ls-multicharacter &&
git clone https://github.com/qbcore-framework/qb-vehiclesales   resources/[ls]/ls-vehiclesales &&
git clone https://github.com/qbcore-framework/qb-vehicleshop   resources/[ls]/ls-vehicleshop &&
git clone https://github.com/qbcore-framework/qb-prison   resources/[ls]/ls-prison &&
git clone https://github.com/project-error/pefcl   resources/[ls]/[pe]/pefcl &&
git clone https://github.com/project-error/qb-pefcl   resources/[ls]/[pe]/ls-pefcl &&
git clone https://github.com/project-error/npwd   resources/[ls]/[pe]/npwd &&
git clone https://github.com/qbcore-framework/qb-npwd   resources/[ls]/[pe]/ls-npwd &&
git clone https://github.com/Project-Sloth/ps-hud   resources/[ls]/[ps]/ls-hud &&
git clone https://github.com/Project-Sloth/ps-ui   resources/[ls]/[ps]/ls-ui &&
git clone https://github.com/Project-Sloth/ps-mdt   resources/[ls]/[ps]/ls-mdt &&
git clone https://github.com/Project-Sloth/ps-dispatch   resources/[ls]/[ps]/ls-dispatch &&
git clone https://github.com/Project-Sloth/ps-drugprocessing   resources/[ls]/[ps]/ls-drugprocessing &&
git clone https://github.com/Project-Sloth/ps-buffs   resources/[ls]/[ps]/ls-buffs &&
git clone https://github.com/Project-Sloth/ps-signrobbery   resources/[ls]/[ps]/ls-signrobbery &&
git clone https://github.com/Project-Sloth/ps-walkingstyle   resources/[ls]/[ps]/ls-walking &&
git clone https://github.com/qbcore-framework/qb-management   resources/[ls]/ls-management &&
git clone https://github.com/qbcore-framework/qb-ambulancejob   resources/[ls]/ls-emergencyservices &&
git clone https://github.com/qbcore-framework/qb-vehiclefailure   resources/[ls]/ls-vehiclefailure &&
git clone https://github.com/qbcore-framework/qb-weathersync   resources/[ls]/ls-weathersync &&
git clone https://github.com/qbcore-framework/qb-policejob   resources/[ls]/ls-policeservices &&
git clone https://github.com/qbcore-framework/qb-apartments   resources/[ls]/ls-apartments &&
git clone https://github.com/qbcore-framework/qb-vehiclekeys   resources/[ls]/ls-vehiclekeys &&
git clone https://github.com/qbcore-framework/qb-mechanicjob   resources/[ls]/ls-vehicleservices &&
git clone https://github.com/qbcore-framework/qb-tunerchip   resources/[ls]/ls-tune &&
git clone https://github.com/qbcore-framework/qb-spawn   resources/[ls]/ls-spawn &&
git clone https://github.com/qbcore-framework/qb-skillbar   resources/[ls]/ls-skillbar &&
git clone https://github.com/qbcore-framework/qb-smallresources   resources/[ls]/ls-pico &&
git clone https://github.com/qbcore-framework/qb-cityhall   resources/[ls]/ls-cityservices &&
git clone https://github.com/qbcore-framework/qb-keyminigame   resources/[ls]/ls-minigame &&
git clone https://github.com/qbcore-framework/qb-commandbinding   resources/[ls]/ls-commandbinds &&
git clone https://github.com/iLLeniumStudios/illenium-appearance   resources/[ls]/ls-appearance &&
git clone https://github.com/qbcore-framework/qb-lockpick   resources/[ls]/ls-lockpick &&
git clone https://github.com/qbcore-framework/qb-interior   resources/[ls]/ls-interior &&
git clone https://github.com/qbcore-framework/qb-menu   resources/[ls]/ls-menu &&
git clone https://github.com/qbcore-framework/qb-input   resources/[ls]/ls-input &&
git clone https://github.com/qbcore-framework/qb-loading   resources/[ls]/ls-loading